#!/usr/bin/env bash

docker tag $IMAGE_NAME $DOCKER_REPO:$SOURCE_COMMIT
docker push $DOCKER_REPO:$SOURCE_COMMIT

docker run -v /etc:/etc $IMAGE_NAME tgbot \
  "image pushed; build log:" \
  "https://cloud.docker.com/repository/registry-1.docker.io/buildah/buildah/builds" \
  "" \
  "Give it a try!" \
  "docker run buildah/buildah:$SOURCE_COMMIT"

echo "------ HOOK END - POST_PUSH -------"

# trigger another build, causing an infinite autobuild loop
curl -X POST 'https://cloud.docker.com/api/build/v1/source/d8d23bee-4df4-4be9-bed7-44230569ba60/trigger/30d292b9-f588-470f-8c09-ddbe606cda3a/call/'
